modification-block-limit: 40960
display-projection: true
tasks:
  block-preview:
    period: 1 # game tick
  displays-clear:
    period: 6000 # game tick
  fill-wand-sui:
    period: 10 # game tick
debug: false