modification-block-limit: 40960
display-projection: true
max-blocks-to-be-preview: 320
preview-range: 20
tasks:
  block-preview:
    period: 5 # game tick
  displays-clear:
    period: 6000 # game tick
  fill-wand-sui:
    period: 10 # game tick
debug: false